- name: Install bat
  become: no
  community.general.homebrew:
    name: bat
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Bat
  package:
    name: bat
    state: present
  when: ansible_facts['os_family'] == 'Debian'

