- name: Install GNU PG Agent
  package:
    name: "gnupg-agent"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Add Docker GPG Key
  apt_key:
    keyserver: "https://download.docker.com/linux/ubuntu/gpg"
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Docker Container Engine
  package:
    name: "docker-ce"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Docker Container CLI
  package:
    name: "docker-ce-cli"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Containerd.io
  package:
    name: "containerd.io"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

