- name: Install Exa
  homebrew:
    name: exa
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Exa
  package:
    name: exa
    state: present
  when: ansible_facts['os_family'] == 'Debian'
