- name: Install fd
  community.general.homebrew:
    name: fd
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install fd
  package:
    name: fd-find
    state: present
  when: ansible_facts['os_family'] == 'Debian'

