- name: Install fzf
  become: no
  community.general.homebrew:
    name: fzf
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  register: fzf

- debug:
    msg: "Remember to run the fzf install script (https://github.com/junegunn/fzf#installation)"
  when: fzf.changed
