- name: Add Google GPG Key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Google Cloud SDK
  package:
    name: "google-cloud-sdk"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Google Cloud Datastore Emulator
  package:
    name: "google-cloud-sdk-datastore-emulator"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Kubectrl
  package:
    name: "kubectl"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Google Cloud SDK
  community.general.homebrew_cask:
    name: google-cloud-sdk
    state: present
  when: ansible_facts['os_family'] == 'Darwin'





