- name: Install Godot
  become: no
  community.general.flatpak_remote:
    name: org.godotengine.Godot
    state: present
    method: user
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Godot
  community.general.homebrew_cask:
    name: godot
    state: present
  when: ansible_facts['os_family'] == 'Darwin'


