- name: Install Kitty
  package:
    name: kitty
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Kitty
  homebrew:
    name: kitty
    state: present
  ignore_errors: yes
  when: ansible_facts['os_family'] == 'Darwin'

- name: Create Kitty configuration directory
  become: no
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/kitty"
    state: directory

- name: Get Kitty Themes
  become: no
  git:
    repo: https://github.com/dexpota/kitty-themes
    dest: "{{ lookup('env', 'HOME') }}/.config/kitty/kitty-themes"
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"

- name: Set Kitty Theme
  become: no
  file:
    src: "{{ lookup('env', 'HOME') }}/.config/kitty/kitty-themes/themes/Afterglow.conf"
    dest: "{{ lookup('env', 'HOME') }}/.config/kitty/theme.conf"
    state: link
    force: yes # initial install of zsh includes .zshrc, so must remove it

