- name: Install Apt Transport HTTPS
  package:
    name: "apt-transport-https"
    state: "present"

- name: Install Postgresql Client
  package:
    name: postgresql-client
    state: present

- name: Install NGINX
  package:
    name: nginx
    state: present

- name: Install Siege
  package:
    name: siege
    state: present

