- name: Install ZSH
  package:
    name: "zsh"
    state: "present"

- name: Install Oh My ZSH
  become: no
  shell: |
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ user }}/.oh-my-zsh"

- name: Install Gnome Tweaks
  package:
    name: "gnome-tweaks"
    state: "present"

- name: Install Apt Transport HTTPS
  package:
    name: "apt-transport-https"
    state: "present"

- name: Install Microsoft PPA
  shell: |
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
    sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
    rm packages.microsoft.gpg
  args:
    creates: /etc/apt/sources.list.d/vscode.list

- name: Install VSCode
  package:
    name: "code"
    state: "present"

- name: Install Tmux
  package:
    name: "tmux"
    state: "present"

- name: Install IO Top
  package:
    name: "iotop"
    state: "present"

- name: Install Rip Grep
  package:
    name: "ripgrep"
    state: "present"

- name: Install HTop
  package:
    name: "htop"
    state: "present"

- name: Install Docker
  include_tasks: docker.yml

- name: Install Neovim
  include_tasks: neovim.yml
