- name: Install Microsoft PPA
  shell: |
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
    sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
    rm packages.microsoft.gpg
  args:
    creates: /etc/apt/sources.list.d/vscode.list

- name: Install RVM PPA
  shell: |
    sudo apt-add-repository -y ppa:rael-gc/rvm
  args:
    creates: /etc/apt/sources.list.d/rael-gc-ubuntu-rvm-focal.list

- name: Install ZSH
  package:
    name: "zsh"
    state: "present"

- name: Install Oh My ZSH
  become: no
  shell: |
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "/home/{{ user }}/.oh-my-zsh"

- name: Install NeoVim
  package:
    name: "neovim"
    state: "present"

- name: Install Gnome Tweaks
  package:
    name: "gnome-tweaks"
    state: "present"

- name: Install Apt Transport HTTPS
  package:
    name: "apt-transport-https"
    state: "present"

- name: Install VSCode
  package:
    name: "code"
    state: "present"

- name: Install Tmux
  package:
    name: "tmux"
    state: "present"

- name: Install IO Top
  package:
    name: "iotop"
    state: "present"

- name: Install Rip Grep
  package:
    name: "ripgrep"
    state: "present"

- name: Install HTop
  package:
    name: "htop"
    state: "present"


### Langauges

- name: Install N
  shell: |
    curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
    chmod +x n
    sudo mv n /usr/bin/n
    bash /usr/bin/n lts
    sudo rm n
  args:
    creates: /usr/bin/n

- name: Install RVM
  package:
    name: "rvm"
    state: "present"

## TODO
#- name: Install Ruby 2.5.7
#  shell: |
#    source /etc/profile.d/rvm.sh
#    rvm install 2.5.7
#  args:
#    creates: /usr/share/rvm/rubies/ruby-2.5.7/
#    
#- name: Install Ruby 2.5.7 Bundler
#  shell: |
#    source /etc/profile.d/rvm.sh
#    rvm use 2.5.7
#    gem install bundler
#  args:
#    executable: /bin/bash
