- import_tasks: postman.yml
- import_tasks: gtk.yml
- import_tasks: terraform.yml
- import_tasks: aws.yml
- import_tasks: gcp_sdk.yml
- import_tasks: kitty.yml
- import_tasks: godot.yml
- import_tasks: docker.yml
- import_tasks: ninja.yml
- import_tasks: bat.yml
- import_tasks: fd.yml

- import_tasks: linux_only.yml
  when: os.type == 'linux'

- import_tasks: osx_only.yml
  when: os.type == 'osx'
