- name: Install Neovim (Linux)
  package:
    name: "neovim"
    state: "present"
  when: ansible_os_family == 'Pop!_OS'

- name: Install Neovim (OSX)
  homebrew:
    name: neovim
    state: present
  when: ansible_os_family == 'Darwin'

- name: Install Vim Plug
  become: no
  shell: |
    sh -c 'curl -fLo "$HOME/.local/share"/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"
