- name: Install Ninja
  homebrew:
    name: ninja
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Ninja
  package:
    name: ninja-build
    state: present
  when: ansible_facts['os_family'] == 'Debian'