- name: Install Postman
  snap:
    name: "postman"
    classic: yes
    state: "present"

- name: Change Postman Icon
  lineinfile:
    path: /var/lib/snapd/desktop/applications/postman_postman.desktop
    regexp: '^Icon='
    line: Icon=postman
