- name: Install Ripgrep
  become: no
  homebrew:
    name: ripgrep
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Rip Grep
  package:
    name: ripgrep
    state: present
  when: ansible_facts['os_family'] == 'Debian'
