- name: Install Terraform Manager
  become: no
  shell: |
    git clone https://github.com/tfutils/tfenv.git /home/{{ lookup('env', 'USER') }}/.tfenv
  args:
    creates: /home/{{ lookup('env', 'USER') }}/.tfenv

- name: Symlink Terraform Manager to /usr/local/bin
  file: 
    src: /home/{{ lookup('env', 'USER') }}/.tfenv/bin/{{ item.src }}
    dest: /usr/local/bin/{{ item.dest }}
    state: link
  loop:
    - { src: 'tfenv', dest: 'tfenv' }
    - { src: 'terraform', dest: 'terraform' }

- name: Install latest version of terraform
  become: no
  shell: |
    /home/{{ lookup('env', 'USER')}}/.tfenv/bin/tfenv install
  args:
    creates: /home/{{ lookup('env', 'USER')}}/.tfenv/versions/
