- name: Install Tig
  become: no
  homebrew:
    name: tig
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Tig
  package:
    name: tig
    state: present
  when: ansible_facts['os_family'] == 'Debian'

