- name: Install Tmux
  package:
    name: "tmux"
    state: "present"
  when: os.type == 'linux'

- name: Install Tmux (OSX)
  homebrew:
    name: tmux
    state: present
  when: os.type == 'osx'

- name: Install Tmux Plugin Manager
  become: no
  shell: |
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  args:
    creates: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"

