- name: Install Tmux (Linux)
  package:
    name: "tmux"
    state: "present"
  when: ansible_os_family == 'Pop!_OS'

- name: Install Tmux (OSX)
  homebrew:
    name: tmux
    state: present
  when: ansible_os_family == 'Darwin'

- name: Install Tmux Plugin Manager
  become: no
  shell: |
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  args:
    creates: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"


