- name: Install Microsoft PPA
  shell: |
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
    sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
    sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
    rm packages.microsoft.gpg
  args:
    creates: /etc/apt/sources.list.d/vscode.list
  when: os.type == 'linux'

- name: Install VSCode
  package:
    name: code
    state: present
  when: os.type == 'linux'

- name: Install VSCode
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  when: os.type == 'osx'

- name: Create a directory if it does not exist
  file:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: staff
    mode: '0755'
  when: os.type == 'osx'


