- name: Install Dropbox
  apt:
    deb: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb"
    state: "present"
  when: ansible_os_family == "Debian"

- name: Install Dropbox
  yum:
    name: "https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2020.03.04-1.fedora.x86_64.rpm"
    state: present
    disable_gpg_check: yes
  when: ansible_os_family == "RedHat"

- name: Install Dropbox
  community.general.homebrew_cask:
    name: dropbox
    state: present
  when: os.type == 'osx'
