- name: Install Chrome
  apt:
    deb: "https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb"
    state: "present"
  when: os.type == 'linux'

- name: Install Zoom
  homebrew_cask:
    name: dropbox
    state: present
  when: os.type == 'osx'
