- name: Add Github GPG Key
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "C99B11DEB97541F0"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Add Github Apt Repo
  apt_repository:
    repo: "deb [arch=amd64] https://cli.github.com/packages {{ ansible_distribution_release }} stable"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Github CLI
  package:
    name: gh
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Github CLI
  community.general.homebrew_cask:
    name: gh
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
