- name: Install Gnome Tweaks
  package:
    name: "gnome-tweaks"
    state: "present"
  when: ansible_os_family == 'Pop!_OS'

- name: Install DConf Editor
  package:
    name: "dconf-editor"
    state: "present"
  when: ansible_os_family == 'Pop!_OS'


