- name: Install Gnome Tweaks
  package:
    name: "gnome-tweaks"
    state: "present"
  when: os.type == 'linux'

- name: Install DConf Editor
  package:
    name: "dconf-editor"
    state: "present"
  when: os.type == 'linux'


