- name: Install Htop
  homebrew:
    name: htop
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Htop
  package:
    name: htop
    state: present
  when: ansible_facts['os_family'] == 'Debian'

