- import_tasks: gnome.yml
- import_tasks: vpn.yml

- name: Install Snap
  package:
    name: "snapd"
    state: "present"
  when: os.type == 'linux'

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install SSH Server
  package:
    name: "openssh-server"
    state: "present"

- name: Install Pidgin
  package:
    name: "pidgin"
    state: "present"

- name: Install Okular
  package:
    name: "okular"
    state: "present"

- name: Install Tor
  package:
    name: "torbrowser-launcher"
    state: "present"

- name: Install Rhythmbox
  package:
    name: rhythmbox
    state: present

- name: Install Gestures
  community.general.flatpak_remote:
    name: gestures
    method: user
    state: present
