- import_tasks: gnome.yml
- import_tasks: vpn.yml
- import_tasks: wine.yml
- import_tasks: xournal.yml

- name: Software Properties Common
  package:
    name: software-properties-common
    state: present

- name: Install SSH Server
  package:
    name: "openssh-server"
    state: "present"

- name: Install Rhythmbox
  package:
    name: rhythmbox
    state: present

- name: Install Gestures
  community.general.flatpak_remote:
    name: gestures
    method: user
    state: present

- name: Install Libnotify (For notify-send cli)
  package:
    name: libnotify-bin
    state: present