- import_tasks: gnome.yml

- name: Software Properties Common
  package:
    name: software-properties-common
    state: present

- name: Install SSH Server
  package:
    name: "openssh-server"
    state: "present"

- name: Install Rhythmbox
  package:
    name: rhythmbox
    state: present

- name: Install Libnotify (For notify-send cli)
  package:
    name: libnotify-bin
    state: present
