- import_tasks: spotify.yml
- import_tasks: dropbox.yml
- import_tasks: slack.yml
- import_tasks: discord.yml
- import_tasks: zoom.yml
- import_tasks: firefox.yml
- import_tasks: wireshark.yml
- import_tasks: vlc.yml
- import_tasks: transmission.yml

- import_tasks: linux_only.yml
  when: os.type == 'linux'

- import_tasks: osx_only.yml
  when: os.type == 'osx'
