- include_tasks: spotify.yml
- include_tasks: dropbox.yml
- include_tasks: slack.yml
- include_tasks: discord.yml
- include_tasks: zoom.yml
- include_tasks: syncthing.yml
- include_tasks: skype.yml
- include_tasks: evernote.yml
- include_tasks: synergy.yml
- include_tasks: chrome.yml

- include_tasks: linux_packages.yml
  when: os.type == 'linux'

- include_tasks: osx_only.yml
  when: os.type == 'osx'

