- include_tasks: spotify.yml
- include_tasks: vivaldi.yml
- include_tasks: slack.yml
- include_tasks: zoom.yml

- name: Install SSHPass
  package:
    name: sshpass
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Mosh
  package:
    name: "mosh"
    state: "present"
  when: ansible_os_family == 'Debian'

- include_tasks: linux_packages.yml
  when: ansible_os_family == 'Debian'

- include_tasks: syncthing.yml
  when: ansible_os_family == 'Debian'
