- include_tasks: spotify.yml
- include_tasks: vivaldi.yml
- include_tasks: slack.yml
- include_tasks: zoom.yml
- include_tasks: microsoft_teams.yml
- include_tasks: syncthing.yml
- include_tasks: skype.yml

- name: Install SSHPass
  package:
    name: sshpass
    state: present
  when: os.type == 'linux'

- name: Install Mosh
  package:
    name: "mosh"
    state: "present"
  when: os.type == 'linux'

- include_tasks: linux_packages.yml
  when: os.type == 'linux'

- include_tasks: osx_only.yml
  when: os.type == 'osx'

