- import_tasks: snap.yml
- import_tasks: flatpak.yml
- import_tasks: zsh.yml
- import_tasks: neovim.yml
- import_tasks: tmux.yml
- import_tasks: vscode.yml
- import_tasks: spotify.yml
- import_tasks: dropbox.yml
- import_tasks: firefox.yml
- import_tasks: wireshark.yml

- import_tasks: linux_only.yml
  when: ansible_facts['os_family'] == 'Debian'

- import_tasks: osx_only.yml
  when: ansible_facts['os_family'] == 'Darwin'
