- name: Install SSH Server
  package: 
    name: "openssh-server"
    state: "present"

- name: Install Mosh
  package:
    name: "mosh"
    state: "present"

- name: Install Gnome Tweaks
  package:
    name: "gnome-tweaks"
    state: "present"

- name: Install DConf Editor
  package: 
    name: "dconf-editor"
    state: "present"

- name: Installs Spotify PPA
  shell: |
    curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add - 
    echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
  args:
    creates: /etc/apt/sources.list.d/spotify.list

- name: Install Spotify
  package:
    name: "spotify-client"
    state: "present"

- name: Install VLC
  snap:
    name: "vlc"
    classic: yes
    state: "present"

- name: Install Vivaldi
  apt: 
    deb: "https://downloads.vivaldi.com/stable/vivaldi-stable_3.1.1929.29-1_amd64.deb"
    state: "present"

- name: Install Zoom
  apt:
    deb: "https://zoom.us/client/latest/zoom_amd64.deb"
    state: "present"

- name: Install Pidgin
  package:
    name: "pidgin"
    state: "present"

- name: Install Okular
  package:
    name: "okular"
    state: "present"
