- import_tasks: rectangle.yml

- name: Install GPG
  homebrew:
    name: gnupg
    state: present

- name: Install Unarchiver
  community.general.homebrew_cask:
    name: the-unarchiver
    state: present

- name: Install Contexts
  community.general.homebrew_cask:
    name: contexts
    state: present

- name: Install Karabiner
  community.general.homebrew_cask:
    name: karabiner-elements
    state: present
