- name: Install GPG
  homebrew:
    name: gnupg
    state: present

- name: Install Unarchiver
  homebrew_cask:
    name: the-unarchiver
    state: present

- name: Install Rectangle
  homebrew_cask:
    name: rectangle
    state: present

- name: Install Contexts
  homebrew_cask:
    name: contexts
    state: present

- name: Install Karabiner
  homebrew_cask:
    name: karabiner-elements
    state: present
