# Install packages that we need to just get up and running

# Install chsh so we can at least change default shell
- name: Install package with chsh command
  package:
    name: util-linux-user
    state: present
  when: when: ansible_facts['os_family'] == 'RedHat'

# Install lsb_release so we can verify things
- name: Install LSB Release command
  package:
    name: redhat-lsb-core
    state: present
  when: when: ansible_facts['os_family'] == 'RedHat'
