- name: Install Skype
  snap:
    name: skype
    classic: yes
    state: present
  when: os.type == 'linux'

- name: Install Skype
  homebrew_cask:
    name: skype
    state: present
  when: os.type == 'osx'
