- name: Install Spotify
  become: no
  flatpak:
    name: com.spotify.Client
    state: present
    method: user
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Spotify
  community.general.homebrew_cask:
    name: spotify
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
