- name: Install Spotify
  community.general.flatpak:
    name: spotify
    state: present
  when: os.type == 'osx'
  
- name: Install Spotify
  homebrew_cask:
    name: spotify
    state: present
  when: os.type == 'osx'
