- name: Install Spotify
  snap:
    name: "spotify"
    state: "present"
  when: os.type == 'linux'

- name: Install Spotify
  homebrew_cask:
    name: spotify
    state: present
  when: os.type == 'osx'
