- name: Installs Spotify PPA
  shell: |
    curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add -
    echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
  args:
    creates: /etc/apt/sources.list.d/spotify.list
  when: os.type == 'linux'

- name: Install Spotify
  package:
    name: "spotify-client"
    state: "present"
  when: os.type == 'linux'

- name: Install Spotify
  homebrew_cask:
    name: spotify
    state: present
  when: os.type == 'osx'
