- name: Install Spotify
  community.general.flatpak_remote:
    name: spotify
    state: present
  when: os.type == 'linux'

- name: Install Spotify
  community.general.homebrew_cask:
    name: spotify
    state: present
  when: os.type == 'osx'
