- name: Install Starship
  become: no
  homebrew:
    name: starship
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Check if starship is already installed
  command: which starship
  register: starship_check
  failed_when: false
  changed_when: false
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Starship prompt
  shell: curl -sS https://starship.rs/install.sh | sh -s -- -y
  when: 
    - starship_check.rc != 0
    - ansible_facts['os_family'] == 'Debian'

