- apt_key:
    url: https://syncthing.net/release-key.txt
    state: present
  when: os.type == 'linux'

- apt_repository:
    repo: deb https://apt.syncthing.net/ syncthing stable
    state: present
  when: os.type == 'linux'

- name: Install Syncthing
  package:
    name: syncthing
    state: present
  when: os.type == 'linux'

- name: Install Syncthing
  community.general.homebrew_cask:
    name: syncthing
    state: present
  when: os.type == 'osx'
