- name: Install Tmux
  package:
    name: "tmux"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Tmux
  homebrew:
    name: tmux
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Tmux Plugin Manager
  become: no
  shell: |
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  args:
    creates: "{{ lookup('env', 'HOME') }}/.tmux/plugins/tpm"

