- apt_repository:
    repo: ppa:transmissionbt/ppa
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Transmission
  package:
    name: transmission
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Transmission
  community.general.homebrew_cask:
    name: transmission
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

