# TODO - update to latest version
#- name: Install Vivaldi
#  apt:
#    deb: "https://downloads.vivaldi.com/stable/vivaldi-stable_3.1.1929.29-1_amd64.deb"
#    state: "present"
#  ignore_errors: yes
#  when: ansible_facts['os_family'] == 'Debian'

- name: Install Vivaldi
  community.general.homebrew_cask:
    name: vivaldi
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
