- name: Install VLC
  snap:
    name: "vlc"
    classic: yes
    state: "present"
  when: os.type == 'linux'

- name: Change VLC Icon
  lineinfile:
    path: /var/lib/snapd/desktop/applications/vlc_vlc.desktop
    regexp: '^Icon='
    line: Icon=vlc
  when: os.type == 'linux'
