- name: Install OpenVPN
  package:
    name: "openvpn"
    state: "present"

- name: Install OpenVPN Gnome GUI
  package:
    name: "network-manager-openvpn-gnome"
    state: "present"
  when: when: ansible_facts['os_family'] == 'Debian'

# Helps with DNS
- name: Install Resolvconf
  package:
    name: "resolvconf"
    state: "present"
