- name: Install Zoom
  apt:
    deb: "https://zoom.us/client/latest/zoom_amd64.deb"
    state: "present"
  when: os.type == 'linux'

- name: Install Zoom
  homebrew_cask:
    name: zoomus
    state: present
  when: os.type == 'osx'
