- name: Install ZSH
  package:
    name: "zsh"
    state: "present"
  when: os.type == 'linux'

- name: Install Oh My ZSH
  become: no
  shell: |
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"

- name: Install ZSH Auto Suggestions
  become: no
  shell: |
    sh -c "git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
