- name: Create a AWS config folder
  file:
    path: "{{ lookup('env', 'HOME') }}/.aws"
    owner: "{{ lookup('env', 'USER') }}"
    state: directory

- name: Copy AWS config 
  copy:
    src: "{{ playbook_dir }}/../configs/aws/config"
    dest: "{{ lookup('env', 'HOME') }}/.aws/config"
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0600'

- name: Copy AWS credentials 
  copy:
    src: "{{ playbook_dir }}/../configs/aws/credentials"
    dest: "{{ lookup('env', 'HOME') }}/.aws/credentials"
    owner: "{{ lookup('env', 'USER') }}"
    mode: '0600'
