- name: Set NeoVim configuration folder
  become: no
  file:
    src: "{{ playbook_dir}}/../configs/nvim-lazyvim/"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: link

- name: Set TMUX configuration file
  become: no
  file:
    src: "{{ playbook_dir }}/../configs/tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link

- name: Set GTK CSS
  become: no
  file:
    src: "{{ playbook_dir }}/../configs/gtk.css"
    dest: "/home/{{ lookup('env', 'USER') }}/.config/gtk-3.0/gtk.css"
    state: link
  when: ansible_facts['os_family'] == 'Debian'

- import_tasks: vscode.yml

- import_tasks: zsh.yml

- import_tasks: zellij.yml
