- name: Create NeoVim configuration directory
  become: no
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: directory

- name: Set NeoVim configuration file
  become: no
  file:
    src: "{{ playbook_dir}}/../configs/nvim.vim"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
    state: link

- name: Set CoC Settings file
  become: no
  file:
    src: "{{ playbook_dir}}/../configs/coc-settings.json"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/coc-settings.json"
    state: link

- name: Set TMUX configuration file
  become: no
  file:
    src: "{{ playbook_dir }}/../configs/tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link

- name: Set GTK CSS
  become: no
  file:
    src: "{{ playbook_dir }}/../configs/gtk.css"
    dest: "/home/{{ lookup('env', 'USER') }}/.config/gtk-3.0/gtk.css"
    state: link
  when: os.type == 'linux'

- import_tasks: vscode.yml

- import_tasks: zsh.yml

- import_tasks: zellij.yml
