- name: Create NeoVim configuration directory
  become: no
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/nvim"
    state: directory

- name: Set NeoVim configuration file
  become: no
  file:
    src: "{{ playbook_dir}}/../configs/nvim.vim"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"
    state: link

- name: Set ZSH configuration file
  become: no
  file:
    src: "{{ playbook_dir }}/../configs/zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link
    force: yes # initial install of zsh includes .zshrc, so must remove it

- name: Set TMUX configuration file
  become: no
  file:
    src: "{{ playbook_dir }}/../configs/tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    state: link

- name: Set GTK CSS
  become: no
  file:
    src: "{{ playbook_dir }}/../configs/gtk.css"
    dest: "/home/{{ lookup('env', 'USER') }}/.config/gtk-3.0/gtk.css"
    state: link
  when: os.type == 'linux'

- name: Set Apple Keyboard shortcuts
  become: no
  file: 
    src: "{{ playbook_dir }}/../configs/com.apple.symbolichotkeys.plist"
    dest: "{{ lookup('env', 'HOME') }}/Library/Preferences/com.apple.symbolichotkeys.plist"
    state: link
    force: yes
  when: os.type == 'osx'

- include_tasks: vscode.yml

- include_tasks: aws.yml
  when: os.type == 'linux'
