- name: Create NeoVim configuration directory
  file: 
    path: "/home/{{ user }}/.config/nvim"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Set NeoVim configuration file 
  file:
    src: "{{ playbook_dir }}/roles/configuration/files/nvim"
    dest: "/home/{{ user }}/.config/nvim/init"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Set TMUX configuration file 
  file:
    src: "{{ playbook_dir }}/roles/configuration/files/tmux.conf"
    dest: "/home/{{ user }}/.tmux.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Set VSCode settings file 
  file:
    src: "{{ playbook_dir }}/roles/configuration/files/code-settings.json"
    dest: "/home/{{ user }}/.config/Code/User/settings.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link


