- name: Create NeoVim configuration directory
  file: 
    path: "/home/{{ lookup('env', 'USER') }}/.config/nvim"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"

- name: Set NeoVim configuration file 
  file:
    src: "{{ playbook_dir }}/configs/nvim.vim"
    dest: "/home/{{ lookup('env', 'USER') }}/.config/nvim/init.vim"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    state: link

- name: Set ZSH configuration file 
  file:
    src: "{{ playbook_dir }}/configs/zshrc"
    dest: "/home/{{ lookup('env', 'USER') }}/.zshrc"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    state: link
    force: yes # initial install of zsh includes .zshrc, so must remove it

- name: Set TMUX configuration file 
  file:
    src: "{{ playbook_dir }}/configs/tmux.conf"
    dest: "/home/{{ lookup('env', 'USER') }}/.tmux.conf"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    state: link

- name: Create VS Code config dir
  file:
    path: "/home/{{ lookup('env', 'USER') }}/.config/Code/User"
    state: directory

- name: Set VSCode settings file 
  file:
    src: "{{ playbook_dir }}/configs/code-settings.json"
    dest: "/home/{{ lookup('env', 'USER') }}/.config/Code/User/settings.json"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    state: link

- name: Set VSCode key bindings file 
  file:
    src: "{{ playbook_dir }}/configs/code-keybindings.json"
    dest: "/home/{{ lookup('env', 'USER') }}/.config/Code/User/keybindings.json"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    state: link

- name: Set GTK CSS  
  file:
    src: "{{ playbook_dir }}/configs/gtk.css"
    dest: "/home/{{ lookup('env', 'USER') }}/.config/gtk-3.0/gtk.css"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    state: link

- name: Copy AWS config 
  copy:
    src: "{{ playbook_dir }}/configs/aws/config"
    dest: "/home/{{ lookup('env', 'USER') }}/.aws/config"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0600'

- name: Copy AWS credentials 
  copy:
    src: "{{ playbook_dir }}/configs/aws/credentials"
    dest: "/home/{{ lookup('env', 'USER') }}/.aws/credentials"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0600'
