- name: Create NeoVim configuration directory
  file: 
    path: "/home/{{ user }}/.config/nvim"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Set NeoVim configuration file 
  file:
    src: "{{ playbook_dir }}/configs/nvim"
    dest: "/home/{{ user }}/.config/nvim/init"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Set TMUX configuration file 
  file:
    src: "{{ playbook_dir }}/configs/tmux.conf"
    dest: "/home/{{ user }}/.tmux.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Set VSCode settings file 
  file:
    src: "{{ playbook_dir }}/configs/code-settings.json"
    dest: "/home/{{ user }}/.config/Code/User/settings.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Set VSCode key bindings file 
  file:
    src: "{{ playbook_dir }}/configs/code-keybindings.json"
    dest: "/home/{{ user }}/.config/Code/User/keybindings.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Set GTK CSS  
  file:
    src: "{{ playbook_dir }}/configs/gtk.css"
    dest: "/home/{{ user }}/.config/gtk-3.0/gtk.css"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link



