- name: Install Steam
  package:
    name: steam
    state: present
  when: os.type == 'linux'

- name: Install Steam
  community.general.homebrew_cask:
    name: steam
    state: present
  when: os.type == 'osx'

- name: Install Godot
  become: no
  community.general.flatpak_remote:
    name: org.godotengine.Godot
    state: present
    method: user
  when: os.type == 'linux'
