- name: Install Steam YUM Repo
  dnf:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_distribution == 'Fedora'

- name: Install Steam
  package:
    name: steam
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Steam
  community.general.homebrew_cask:
    name: steam
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

