- name: Set Fedora Version
  shell: rpm -E %fedora
  register: fedora_version
  when: ansible_distribution == 'Fedora'

- name: Install Steam YUM Repo
  dnf:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_distribution == 'Fedora'

- name: Install Steam
  package:
    name: steam
    state: present
  when: os.type == 'linux'

- name: Install Steam
  community.general.homebrew_cask:
    name: steam
    state: present
  when: os.type == 'osx'

