- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  when:
    - ansible_facts['os_family'] == "Debian" 

- name: "Add nodejs {{ node_major_version }}.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ node_major_version }}.x {{ debian_distro }} main
    update_cache: yes
  when:
    - ansible_facts['os_family'] == "Debian" 

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present
  when:
    - ansible_facts['os_family'] == "Debian" 

