# TODO Must run:
# sudo dpkg-reconfigure libdvd-pkg
# After installation of libdvdcss2
- name: "Install Libdvdcss"
  package:
    name: "libdvdcss2"
    state: "present"

- name: "Install Handbrake"
  package:
    name: "handbrake"
    state: "present"

- name: "Install MakeMKV"
  snap:
    name: "makemkv"
    classic: yes
    state: "present"

- name: Install CCExtractor
  package:
    name: ccextractor
    state: present

- name: Add Plex Server Apt Key
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key 
    state: present

- name: Add Plex Server PPA
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present

- name: Install Plex Server
  package:
    name: plexmediaserver
    state: present

