- name: Install NFS Server
  package:
    name: nfs-kernel-server
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Setup Share Folder
  file:
    path: /mnt/share
    owner: nobody
    group: nogroup
    mode: '0777'
    state: directory
  when: ansible_facts['os_family'] == 'Debian'

- name: Setup Exports
  file:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['os_family'] == 'Debian'

