- name: Install Zafiro Icons
  become: no
  shell: |
    export VERSION=1.1
    wget --quiet -O /tmp/zafiro-icons.tar.gz https://github.com/zayronxio/Zafiro-icons/archive/$VERSION.tar.gz
    cd /tmp
    tar xf zafiro-icons.tar.gz
    mkdir -p ~/.local/share/icons/Zafiro-Icons
    cp -r Zafiro-icons-$VERSION/* ~/.local/share/icons/Zafiro-Icons/
    rm -rf zafiro-icons.tar.gz Zafiro-icons-$VERSION
  args:
    creates: /home/{{ lookup('env', 'USER') }}/.local/share/icons/Zafiro-Icons
  when: os.type == 'linux'

- name: Install Oogir Icons
  become: no
  shell: |
    export ICON_DIR=qogir-icons
    cd /tmp
    git clone https://github.com/vinceliuice/Qogir-icon-theme $ICON_DIR
    cd $ICON_DIR
    ./install.sh
    cd ../
    rm -rf $ICON_DIR
  args:
    creates: /home/{{ lookup('env', 'USER') }}/.local/share/icons/Qogir
  when: os.type == 'linux'

- apt_repository:
    repo: ppa:papirus/papirus
  when: os.type == 'linux'

- name: Install Papirus Icons
  package:
    name: papirus-icon-theme
    state: present
  when: os.type == 'linux'
