- name: Install Discord
  snap:
    name: discord
    classic: yes
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Change Discord Icon
  lineinfile:
    path: /var/lib/snapd/desktop/applications/discord_discord.desktop
    regexp: '^Icon='
    line: Icon=discord
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Discord
  community.general.homebrew_cask:
    name: discord
    state: present
  when: ansible_facts['os_family'] == 'Darwin' and is_corp is defined and is_corp
