- name: Install Skype
  snap:
    name: skype
    classic: yes
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Skype
  community.general.homebrew_cask:
    name: skype
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
