- name: Install Slack
  package:
    name: slack-desktop
    state: present
  when: os.type == 'linux'

- name: Install Slack
  community.general.homebrew_cask:
    name: slack
    state: present
  when: os.type == 'osx' and name != 'ecorp'
  ignore_errors: yes
