- name: Install Slack
  package:
    name: slack-desktop
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Slack
  community.general.homebrew_cask:
    name: slack
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
