- name: Install Zoom
  apt:
    deb: "https://zoom.us/client/latest/zoom_amd64.deb"
    state: "present"
  when: ansible_facts['os_family'] == 'Debian'

- name: Add Zoom RPM Key
  rpm_key:
    state: present
    key: https://zoom.us/linux/download/pubkey
  when: ansible_os_family == "RedHat"

- name: Install Zoom
  yum:
    name: "https://zoom.us/client/latest/zoom_x86_64.rpm"
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Zoom
  community.general.homebrew_cask:
    name: zoomus
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
