- name: Install Musescore
  become: no
  community.general.flatpak:
    name: musescore
    method: user
    remote: flathub
    state: present
  when: os.type == 'linux'

- name: Install Musescore
  community.general.homebrew_cask:
    name: musescore
    state: present
  when: os.type == 'osx'

