- name: Install Musescore
  snap:
    name: musescore
    state: present
  when: os.type == 'linux'

- name: Install Musescore
  homebrew_cask:
    name: musescore
    state: present
  when: os.type == 'osx'

