- hosts: all
  become: yes
  vars:
    nfs:
      server: true
  roles:
    - { role: always }
    - { role: basics }
    - { role: cron }
    - { role: communication }
    - { role: games }
    - { role: developer }
    - { role: languages }
    - { role: sound }
    - { role: movies }
    - { role: art }
    - { role: fonts }
    - { role: configuration }
    - { role: themes }
    - { role: post_run }
  tasks:
    - include_tasks: ../roles/basics/tasks/zsa.yml

