- hosts: all
  become: yes
  vars:
    name: ecorp
    os:
      type: osx
    is_corp: true
  roles:
    - { role: always }
    - { role: basics, become: no }
    - { role: communication, become: no }
    - { role: developer, become: no }
    - { role: languages, become: no }
    - { role: configuration, become: no }

