- hosts: all
  become: yes
  vars:
    nfs:
      server: true
      client: false
  roles:
    - { role: always }
    - { role: basics, become: no }
    - { role: developer, become: no }
    - { role: configuration, become: no }

