- hosts: all
  become: yes
  vars:
   os:
      type: osx
  roles:
    - { role: always }
    - { role: basics, become: no }
    - { role: developer, become: no }
    - { role: communication, become: no }
    - { role: art, become: no }
    - { role: games, become: no }
    - { role: sound, become: no }
    - { role: configuration, become: no }

