- hosts: all
  become: yes
  vars:
    os:
      type: linux
  roles:
    - { role: always }
    - { role: basics }
    - { role: developer }
    - { role: art  }
    - { role: configuration }
    - { role: post_run }

