- hosts: all
  become: no
  vars:
    name: zr
    os:
      type: osx
  tasks:
    - include_tasks: ../roles/basics/tasks/htop.yml
    - include_tasks: ../roles/basics/tasks/tmux.yml
    - include_tasks: ../roles/basics/tasks/neovim.yml
    - include_tasks: ../roles/basics/tasks/rectangle.yml
    - include_tasks: ../roles/basics/tasks/karabiner.yml

    # Languages
    - include_tasks: ../roles/languages/tasks/javascript.yml
  roles:
    - { role: developer }
    - { role: configuration }