- name: Register the current Go version
  stat:
    path: /usr/local/go
  register: go_installation

- name: Download the Go tarball
  get_url:
    url: "{{ go_download_location }}"
    dest: /usr/local/src/{{ go_tarball }}
    checksum: "{{ go_tarball_checksum }}"
  when: not go_installation.stat.exists

- name: Extract the Go tarball
  unarchive:
    src: /usr/local/src/{{ go_tarball }}
    dest: /usr/local
    copy: no
  when: not go_installation.stat.exists
