- name: Install N
  shell: |
    curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o n
    chmod +x n
    sudo mv n /usr/bin/n
    bash /usr/bin/n lts
  args:
    creates: /usr/bin/n
  when: ansible_facts['os_family'] == 'Debian'

- name: Install N
  homebrew:
    name: n
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
