- name: Install PyEnv
  become: no
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "/home/{{ lookup('env', 'USER') }}/.pyenv"
    version: master
  register: git_result
  changed_when: "git_result.after|default('after') != git_result.before|default('before')"
  when: os.type == 'linux'