# Aseprite will be installed via Steam
# But let's modify the steam Desktop file
# so that it runs Asesprite directly
# instead of running Steam first

- name: Check that the somefile.conf exists
  stat:
    path: aseprite['launcher_path']
  register: launcher_file

- name: Change Aseprite Steam Executable Path
  lineinfile:
    path: aseprite['launcher_path']
    regexp: '^Exec='
    line: "Exec={{ lookup('env', 'HOME') }}/.steam/steam/steamapps/common/Aseprite/aseprite"
    create: no
  when: ansible_facts['os_family'] == 'Debian' and launcher_file.stat.exists
