- name: Install Blender
  snap:
    name: blender
    classic: yes
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Blender
  package:
    name: blender
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

#- name: Change Blender Icon
#  lineinfile:
#    path: /var/lib/snapd/desktop/applications/blender_blender.desktop
#    regexp: '^Icon='
#    line: Icon=blender
#  when: ansible_facts['os_family'] == 'Debian'

- name: Install Blender
  community.general.homebrew_cask:
    name: blender
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
