- name: Install the Gimp flatpak
  become: no
  flatpak:
    name:  https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref
    state: present
    method: user
  when: os.type == 'linux'

- name: Install Gimp
  community.general.homebrew_cask:
    name: gimp
    state: present
  when: os.type == 'osx'
