- name: Install Gimp
  package:
    name: gimp
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Gimp
  community.general.homebrew_cask:
    name: gimp
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
