- name: Install Gimp
  package:
    name: gimp
    state: present
  when: os.type == 'linux'

- name: Install Gimp
  community.general.homebrew_cask:
    name: gimp
    state: present
  when: os.type == 'osx'
