- apt_repository:
    repo: ppa:inkscape.dev/stable
  when: when: ansible_facts['os_family'] == 'Debian'

- name: Install Inkscape
  package:
    name: inkscape
    state: present
  when: ansible_facts['os_family'] == 'Debian'

# Inkscape is currently unbearably slow on OSX
# Hopefully one day this can be fixed
#
#- name: Install Inkscape
#  community.general.homebrew_cask:
#    name: inkscape
#    state: present
#  when: ansible_facts['os_family'] == 'Darwin'
