- apt_repository:
    repo: ppa:kritalime/ppa
  when: ansible_os_family == 'Debian'

- name: Install Krita
  package:
    name: krita
    state: present
  when: os.type == 'linux'

- name: Install Krita
  community.general.homebrew_cask:
    name: krita
    state: present
  when: os.type == 'osx'
