- apt_repository:
    repo: ppa:kritalime/ppa
  when: when: ansible_facts['os_family'] == 'Debian'

- name: Install Krita
  package:
    name: krita
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install Krita
  community.general.homebrew_cask:
    name: krita
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
