- name: Install the Gimp flatpak
  become: no
  flatpak:
    name:  https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref
    state: present
    method: user

- apt_repository: 
    repo: ppa:inkscape.dev/stable

- name: Install Inkscape
  package:
    name: inkscape
    state: present

- apt_repository: 
    repo: ppa:kritalime/ppa

- name: Install Krita
  package: 
    name: krita
    state: present
    
- name: Install Blender
  snap:
    name: blender
    classic: yes
    state: present
